---
linters:
  PropertySortOrder:
    order: smacss
  PseudoElement:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  StringQuotes:
    enabled: false
  UnnecessaryParentReference:
    enabled: false
